model_strategy: Strategy.LM_LOSS | Strategy.LOGITS_KL_DIV

cls:
  _target_: src.shift_encoder.AttnFFNShift
  attn_strategy: null
  ffn_strategy: ShiftStrategy.VECTOR_SHIFT | ShiftStrategy.LEARNABLE_SHIFT_SCALE
  shift_scale_init_value: 0.1

