model_strategy: Strategy.LM_LOSS | Strategy.LAYER_WISE_MSE

cls:
  _target_: src.shift_encoder.AttnApproximator
  attn_strategy: ShiftStrategy.USE_VECTOR_IMPL | ShiftStrategy.LEARNABLE_SHIFT_SCALE | ShiftStrategy.MULTI_HEAD
  ffn_strategy: ShiftStrategy.RECORD_HIDDEN_STATES
