defaults:
  - _self_
  - exp_settings

runname: "default"
resume: True
lr: ${peft.lr}
weight_decay: 1e-3
warmup_step: 0.1
batch_size: 2
epochs: null # int or null. if null, decide by train.py
ce_loss_weight: ${peft.ce_loss_weight}
align_loss_weight: ${peft.align_loss_weight}
strategy: auto  # Options: "deepspeed_stage_2_offload" / "ddp"
accumulate_grad_batches: 4
grad_clip_val: 1
precision: 32-true